name: "Modbus to MQTT Bridge"
version: "1.0.24"
slug: "modbus_mqtt_bridge"
description: "Bridge Modbus RTU-over-TCP devices to Home Assistant via MQTT"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 8099
options:
  mqtt_broker: "192.168.50.106"
  mqtt_port: 1883
  mqtt_username: "mqqt"
  mqtt_password: "mqqt"
  mqtt_topic_prefix: "usr_n580_bridge"
  mqtt_discovery_prefix: "homeassistant"
  modbus_host: "192.168.50.96"
  modbus_port: 41
  poll_interval: 15
  log_level: "info"
  retries: 3
  delay_between_requests: 0.1
  max_gap: 10
schema:
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: password?
  mqtt_topic_prefix: str
  mqtt_discovery_prefix: str
  modbus_host: str
  modbus_port: int
  poll_interval: int
  log_level: "list(debug|info|warning|error)"
  retries: int?
  delay_between_requests: float?
  max_gap: int?

